/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ws_bank_client;

import customer_ws.Customers;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Keshav
 */
public class Customer_List extends javax.swing.JFrame {

    List<Customers> cust_list = new ArrayList();
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();


    /**
     * Creates new form Customer_List
     */
    public Customer_List() {
        initComponents();
        getContentPane().setBackground(new Color(255, 255, 255));
        cust_list = showCustomers();
        displayCustomers();
    }

    public void displayCustomers() {
        custList.setLayout(new GridLayout(0, 3));
        JLabel lblName = new JLabel("Name");
        lblName.setForeground(Color.black);
        lblName.setFont(new Font("Roboto", Font.PLAIN, 18));
        lblName.setBorder(BorderFactory.createLineBorder(Color.white));
        JLabel lblAccNumber = new JLabel("Account Number");
        lblAccNumber.setForeground(Color.BLACK);
        lblAccNumber.setFont(new Font("Roboto", Font.PLAIN, 18));
        lblAccNumber.setBorder(BorderFactory.createLineBorder(Color.WHITE));
        JLabel lblManage = new JLabel("");
        lblManage.setBorder(BorderFactory.createLineBorder(Color.WHITE));
        custList.add(lblName);
        custList.add(lblAccNumber);
        custList.add(lblManage);
        JButton[] buttons = new JButton[cust_list.size()];
        JLabel[] nameLabels = new JLabel[cust_list.size()];
        JLabel[] accNumberLabels = new JLabel[cust_list.size()];
        for (int i = 0; i < cust_list.size(); i++) {
            buttons[i] = new JButton();
            nameLabels[i] = new JLabel(cust_list.get(i).getName());
            accNumberLabels[i] = new JLabel(cust_list.get(i).getAccountNumber());
            buttons[i].setText("Manage");
            buttons[i].setFont(new Font("Roboto", Font.PLAIN, 18));
            buttons[i].setBorder(BorderFactory.createLineBorder(Color.WHITE));
            nameLabels[i].setHorizontalAlignment(SwingConstants.CENTER);
            accNumberLabels[i].setHorizontalAlignment(SwingConstants.CENTER);
            Customers tempCust = cust_list.get(i);
            buttons[i].addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    setVisible(false);
                    new CustomerAccount(tempCust).setVisible(true);
                }
            });
            nameLabels[i].setForeground(Color.BLACK);
            nameLabels[i].setFont(new Font("Roboto", Font.PLAIN, 18));
            nameLabels[i].setBorder(BorderFactory.createLineBorder(Color.BLACK));
            accNumberLabels[i].setForeground(Color.BLACK);
            accNumberLabels[i].setFont(new Font("Roboto", Font.PLAIN, 18));
            accNumberLabels[i].setBorder(BorderFactory.createLineBorder(Color.BLACK));
            custList.add(nameLabels[i]);
            custList.add(accNumberLabels[i]);
            custList.add(buttons[i]);
        }
        add(custList);
        custList.revalidate();
        custList.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        custList = new javax.swing.JPanel();
        btnCreateCust = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        custList.setBackground(new java.awt.Color(255, 255, 255));
        custList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18), new java.awt.Color(0, 102, 255))); // NOI18N
        custList.setForeground(new java.awt.Color(255, 255, 255));
        custList.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        javax.swing.GroupLayout custListLayout = new javax.swing.GroupLayout(custList);
        custList.setLayout(custListLayout);
        custListLayout.setHorizontalGroup(
            custListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        custListLayout.setVerticalGroup(
            custListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        btnCreateCust.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnCreateCust.setText("Create a New Customer");
        btnCreateCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCustActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(custList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateCust)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                        .addComponent(btnLogout)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(custList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateCust)
                    .addComponent(btnLogout))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCustActionPerformed
        this.setVisible(false);
        new CustomerAccount().setVisible(true);
    }//GEN-LAST:event_btnCreateCustActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.setVisible(false);
        new Index().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_List().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCust;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel custList;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<customer_ws.Customers> showCustomers() {
        customer_ws.CustomerWs_Service service = new customer_ws.CustomerWs_Service();
        customer_ws.CustomerWs port = service.getCustomerWsPort();
        return port.showCustomers();
    }

}
